acac_backend/src/acac_backend/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.auth.decorators import user_passes_test
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.views.decorators.csrf import csrf_exempt

from acac_backend.schema import PrivateGraphQLView, PublicGraphQLView
from acac_backend.views import FrontendUpdateView, VueView
from oauth.views import SessionView

admin.site.site_title = 'Gymkhana Administration'
admin.site.site_header = 'Gymkhana Administration'
admin.site.index_title = 'Control Panel'

urlpatterns = [
    url(r'^logout/$', LogoutView.as_view(next_page='login'),
        name='logout'),
    url(r'^session/$', SessionView.as_view(), name='session'),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frontend-upload/',
        user_passes_test(lambda u: u.is_superuser, login_url='admin:login')(
            FrontendUpdateView.as_view()),
        name='admin-frontend-upload'),
    path('', include('social_django.urls', namespace='social')),
]

urlpatterns += [
    path("graphql", csrf_exempt(PublicGraphQLView.as_view(graphiql=True))),
    path("pgraphql", csrf_exempt(PrivateGraphQLView.as_view(graphiql=True)))
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'.*', VueView.as_view(), name='vue-js')]

acac_backend/src/forum/api/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum_api'

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/upvote/$', views.TopicUpvoteAPIToggle.as_view(), name='topic-upvote-toggle'),
    url(r'^answer/(?P<id>\d+)/upvote/$', views.AnswerUpvoteAPIToggle.as_view(), name='answer-upvote-toggle'),
    # url(r'^topic/(?P<pk>\d+)/$', views.TopicDetailView.as_view(), name='detail'),
    # url(r'^topic/add/$', views.TopicCreateView.as_view(), name='add_topic'),
    # url(r'^topic/(?P<pk>\d+)/update/$', views.TopicUpdateView.as_view(), name='update_topic'),
    # url(r'^topic/(?P<pk>\d+)/delete/$', views.TopicDeleteView.as_view(), name='delete_topic'),
    # url(r'^test/$', views.test, name='test'),
]

acac_backend/src/forum/urls.py
from django.conf.urls import url
from forum import views

app_name = 'forum'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^answered-by-me/$', views.AnswerView.as_view(), name='answered-by-user'),
    url(r'^topic/add/$', views.TopicCreateView.as_view(), name='add_topic'),
    url(r'^(?P<slug>[\w-]+)/$', views.TopicDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/update/$', views.TopicUpdateView.as_view(), name='update_topic'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.TopicDeleteView.as_view(), name='delete_topic'),
    url(r'^answer/(?P<pk>\d+)/delete/$', views.AnswerDeleteView.as_view(), name='delete_answer'),
    url(r'^test/$', views.test, name='test'),
]

acac_backend/src/konnekt/urls.py
from django.conf.urls import url
from .views import HomeView, SearchView

app_name = 'konnekt'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^search/$', SearchView.as_view(), name='search'),
]

acac_backend/src/main/urls.py
from django.conf.urls import url
from .views import HomeView, BoardView, SocietyView, SenateView, ContactListView, ContactView, OfficeView

app_name = 'main'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^office-bearers/$', OfficeView.as_view(), name='office-bearers'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^contact_list/$', ContactListView.as_view(), name='contact_list'),
    url(r'^board/(?P<slug>[\w-]+)/$', BoardView.as_view(), name='board-detail'),
    url(r'^senate/(?P<slug>[\w-]+)/$', SenateView.as_view(), name='senate-detail'),
    url(r'^society/(?P<slug>[\w-]+)/$', SocietyView.as_view(), name='society-detail'),
]

acac_backend/src/forum/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from .utils import unique_slug_generator
from oauth.models import UserProfile
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from hitcount.models import HitCountMixin


class TopicQueryset(models.query.QuerySet):
    def search(self, query):
        if query:
            return self.filter(
                Q(author__user__first_name__icontains=query) |
                Q(author__user__last_name__icontains=query) |
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(tags__icontains=query) |
                Q(answer__content__icontains=query)
            ).distinct()
        else:
            return self.none()


class TopicManager(models.Manager):
    def get_topic_queryset(self):
        return TopicQueryset(self.model, using=self._db)

    def search(self, query):
        return self.get_topic_queryset().search(query)


class Topic(models.Model, HitCountMixin):
    # Choices
    CAT_CHOICES = (
        ('Q', 'Question'),
        ('F', 'Feedback'),
        ('S', 'Suggestion'),
        ('I', 'Improvement'),
    )
    # Topic Database Model
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="author of topic")
    category = models.CharField(max_length=3, choices=CAT_CHOICES, default='Q')
    title = models.CharField(max_length=256)
    content = RichTextUploadingField()
    tags = models.CharField(max_length=50, blank=True, null=True, default=None)
    upvotes = models.ManyToManyField(UserProfile, blank=True, related_name='topic_upvotes')
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    objects = TopicManager()

    @property
    def number_of_answers(self):
        return self.answer_set.count()

    class Meta:
        ordering = ["-created_at"]

    def get_absolute_url(self):
        return reverse('forum:detail', kwargs={'slug': self.slug})

    def get_api_upvote_toggle_url(self):
        return reverse('forum_api:topic-upvote-toggle', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('forum:update_topic', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('forum:delete_topic', kwargs={'slug': self.slug})

    def tags_as_list(self):
        if self.tags == '' or not self.tags:
            return ''
        return sorted(self.tags.split(','))

    def __str__(self):
        return self.title


def topic_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(topic_pre_save_receiver, sender=Topic)


class Answer(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name="topic of answer")
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="author of answer")
    content = RichTextUploadingField(blank=True)
    upvotes = models.ManyToManyField(UserProfile, blank=True, related_name='answer_upvotes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def get_api_upvote_toggle_url(self):
        return reverse('forum_api:answer-upvote-toggle', kwargs={'id': self.id})

    def get_absolute_url(self):
        return self.topic.get_absolute_url()

    def get_delete_url(self):
        return reverse('forum:delete_answer', kwargs={'pk': self.pk})

    def __str__(self):
        return "On: " + str(self.topic.title) + " by " + str(self.author.user.first_name) + " " + str(
            self.author.user.last_name)

acac_backend/src/forum/forms.py
from django import forms
from .models import Topic, Answer
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.utils.html import strip_tags


class TopicForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Topic
        fields = ['category', 'title', 'tags', 'content']


class AnswerForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Answer
        fields = ('topic', 'author', 'content')

    def clean_content(self):
        content = strip_tags(self.data['content']).split()
        content = [x for x in content if x != '&nbsp;']
        if len(content) == 0:
            raise forms.ValidationError('This field is required')
        else:
            return self.data['content']

acac_backend/src/forum/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from forum.models import Topic, Answer
from django.shortcuts import get_object_or_404


class TopicUpvoteAPIToggle(APIView):
    def get(self, request, slug=None, format='json'):
        obj = get_object_or_404(Topic, slug=slug)
        user = self.request.user
        updated = False
        upvoted = False
        if user.is_authenticated:
            if user.userprofile in obj.upvotes.all():
                obj.upvotes.remove(user.userprofile)
                upvoted = False
            else:
                obj.upvotes.add(user.userprofile)
                upvoted = True
            updated = True
        data = {
            'updated': updated,
            'upvoted': upvoted
        }
        return Response(data)


class AnswerUpvoteAPIToggle(APIView):
    def get(self, request, id=None, format=None):
        obj = get_object_or_404(Answer, id=id)
        user = self.request.user
        updated = False
        upvoted = False
        if user.is_authenticated:
            if user.userprofile in obj.upvotes.all():
                obj.upvotes.remove(user.userprofile)
                upvoted = False
            else:
                obj.upvotes.add(user.userprofile)
                upvoted = True
            updated = True
        data = {
            'updated': updated,
            'upvoted': upvoted
        }
        return Response(data)

acac_backend/src/forum/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, FormView, View
from django.views.generic.detail import SingleObjectMixin
from .models import Topic, Answer
from .forms import TopicForm, AnswerForm
from django.urls import reverse_lazy
from django.shortcuts import render, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from hitcount.views import HitCountDetailView
from .mixins import UserAuthorMixin


class IndexView(LoginRequiredMixin, ListView):
    template_name = 'forum/index.html'
    context_object_name = 'topic_list'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['range'] = range(context["paginator"].num_pages)
        return context

    def get_queryset(self):
        if self.request.GET.get('q'):
            query = self.request.GET.get('q')
            return Topic.objects.search(query)
        else:
            return Topic.objects.all()


class AnswerView(LoginRequiredMixin, ListView):
    template_name = 'forum/answerd_by_user.html'
    context_object_name = 'topic_list'
    paginate_by = 20

    def get_queryset(self):
        return Topic.objects.filter(author=self.request.user.userprofile)

    def get_context_data(self, **kwargs):
        context = super(AnswerView, self).get_context_data(**kwargs)
        context['range'] = range(context["paginator"].num_pages)
        return context


class TopicDisplay(HitCountDetailView, DetailView):
    count_hit = True
    model = Topic
    context_object_name = 'topic'
    template_name = 'forum/topic_detail.html'

    def get_context_data(self, **kwargs):
        context = super(TopicDisplay, self).get_context_data(**kwargs)
        context['answer_list'] = self.object.answer_set.all()
        context['form'] = AnswerForm()
        return context


class TopicAnswer(LoginRequiredMixin, SingleObjectMixin, FormView):
    template_name = 'forum/topic_detail.html'
    form_class = AnswerForm
    model = Topic

    def get_context_data(self, **kwargs):
        context = super(TopicAnswer, self).get_context_data(**kwargs)
        context['answer_list'] = self.object.answer_set.all()
        return context

    def form_valid(self, form):
        form.save()
        return super(TopicAnswer, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(TopicAnswer, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()


class TopicDetailView(LoginRequiredMixin, HitCountDetailView, View):

    def get(self, request, *args, **kwargs):
        view = TopicDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = TopicAnswer.as_view()
        return view(request, *args, **kwargs)


class TopicCreateView(LoginRequiredMixin, CreateView):
    form_class = TopicForm
    template_name = 'forum/topic_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user.userprofile
        return super(TopicCreateView, self).form_valid(form)


class TopicUpdateView(UserAuthorMixin, UpdateView):
    model = Topic
    form_class = TopicForm
    template_name = 'forum/topic_form_edit.html'


class TopicDeleteView(UserAuthorMixin, DeleteView):
    model = Topic
    success_url = reverse_lazy('forum:index')

    def get(self, request, *args, **kwargs):
        raise Http404


class AnswerDeleteView(UserAuthorMixin, DeleteView):
    model = Answer

    def get(self, request, *args, **kwargs):
        raise Http404

    def get_success_url(self):
        return self.get_object().get_absolute_url()


@login_required
def test(request):  # pragma: no use
    return render(request, 'forum/test.html')

acac_backend/src/templates/forum/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block metatags %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% endblock %}
    <title>{% block title %}Students' Gymkhana Forum{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    {% block mdbcss %}
        <link rel="stylesheet" href="{% static 'css/compiled.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/mdbadmin.min.css' %}">
    {% endblock %}
    <link rel="icon" href="/static/assets/default-favicon.ico">
    {% block customstyles %}
    {% endblock %}
</head>
<body class="fixed-sn {% block skin %}white-skin{% endblock %}">
{% block header %}
    <!--Double navigation-->
    <header>
        {% block sidenavcontent %}
            <!-- Sidebar navigation -->
            <ul id="slide-out" class="side-nav fixed sn-bg-1 custom-scrollbar">
                <!-- Logo -->
                <li class="li-user-view">
                    <div class="background">
                        <img src="{% include 'oauth/mixins/user_cover_src_small_mixin.html' with userprofile=request.user.userprofile %}">
                    </div>
                    <div class="hm-black-light">
                        <div class="user-view mask">
                            <div><img class="circle" src="


                                    {% if request.user.userprofile.avatar %}{{ request.user.userprofile.avatar.crop.64x64 }}{% else %}{% static 'assets/others/missing.png' %}{% endif %}">
                            </div>
                            <div><span class="white-text name">{{ request.user.get_full_name }}</span></div>
                            <div><span class="white-text email">{{ request.user.email }}</span></div>
                        </div>
                    </div>
                </li>
                <!--/. Logo -->
                <br>
                {% block sidenavlower %}
                    <!-- Side navigation categories -->
                    <li>
                        <ul id="side-menu" class="collapsible collapsible-accordion">
                            <li id="menu-item-12031"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-12031">
                                <a class="collapsible-header waves-effect"
                                   href="{{ request.user.userprofile.get_absolute_url }}">
                                    <i class="fa fa-user"></i>
                                    Profile</a></li>
                            <li id="menu-item-13028"
                                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-13028">
                                <a class="collapsible-header waves-effect arrow-r">
                                    <i class="fa fa-database" aria-hidden="true"></i>
                                    Categories
                                    <i class="fa fa-angle-down rotate-icon rotate-element">
                                    </i></a>
                                <div class="collapsible-body" style="display: none;">
                                    <ul class="sub-menu">
                                        <li id="menu-item-338"
                                            class="menu-item menu-item-type-post_type menu-item-object-page  menu-item-338">
                                            <a class="collapsible-header waves-effect" href="{% url 'forum:index' %}">All
                                                Questions</a></li>
                                        <li id="menu-item-338"
                                            class="menu-item menu-item-type-post_type menu-item-object-page  menu-item-338">
                                            <a class="collapsible-header waves-effect"
                                               href="{% url 'forum:answered-by-user' %}">Answered By You</a></li>
                                    </ul>
                                </div>
                            </li>
                            {% comment %}<li id="menu-item-12031"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-12031">
                                <a class="collapsible-header waves-effect" href="#">
                                    <i class="fa fa-calendar"></i>
                                    Events</a></li>{% endcomment %}
                            <li id="menu-item-12031"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-12031">
                                <a class="collapsible-header waves-effect" href="{% url 'main:index' %}">
                                    <i class="fa fa-home"></i>
                                    Home</a></li>
                            <li id="menu-item-12031"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-12031">
                                <a class="collapsible-header waves-effect" href="#">
                                    <i class="fa fa-question-circle"></i>
                                    Help</a></li>
                            <li id="menu-item-12031"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-12031">
                                <a class="collapsible-header waves-effect" href="#">
                                    <i class="fa fa-info"></i>
                                    About</a></li>
                        </ul>
                    </li>
                    <!--/. Side navigation categories -->
                {% endblock %}
                <div class="sidenav-bg mask-strong"></div>
            </ul>
        {% endblock %}
        <!--/. Sidebar navigation -->
        {% block navbar %}
            <!-- Navbar -->
            <nav class="navbar fixed-top navbar-toggleable-md navbar-dark scrolling-navbar double-nav">
                <!-- SideNav slide-out button -->
                <div class="float-left">
                    <a href="#" data-activates="slide-out" class="button-collapse"><i class="fa fa-bars"></i></a>
                </div>
                <!-- Breadcrumb-->
                <div class="breadcrumb-dn mr-auto ml-3">
                    <h5 class="h5-responsive">{% block navtitle %}Breadcrumb or page title{% endblock %}</h5>
                </div>
                <ul class="nav navbar-nav nav-flex-icons ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'forum:index' %}" class="nav-link"><i class="fa fa-home"></i> <span
                                class="hidden-sm-down">Forum</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'konnekt:index' %}" class="nav-link"><i class="fa fa-handshake-o"></i> <span
                                class="hidden-sm-down">Konnekt</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="account" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            <i class="fa fa-user"></i> <span class="hidden-sm-down">Account</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="account">
                            <a class="dropdown-item"
                               href="{{ request.user.userprofile.get_absolute_url }}">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- /.Navbar -->
        {% endblock %}
    </header>
    <!--/.Double navigation-->
{% endblock %}
<!--Content-->
{% block content %}
    <main>
        {% block main %}
            <div class="container-fluid">
                <div style="height: 2000px"></div>
            </div>
        {% endblock %}
    </main>
{% endblock %}
<!--Footer-->
{% block footer %}
    <!--Footer-->
    <footer class="page-footer center-on-small-only pt-0">
        {% comment %}<!--Footer Links-->
        <div class="container-fluid">
            <div class="row">

                <!--First column-->
                <div class="col-md-3 offset-md-1">
                    <h5 class="title">Footer Content</h5>
                    <p>Here you can use rows and columns here to organize your footer content.</p>
                </div>
                <!--/.First column-->

                <hr class="hidden-md-up">

                <!--Second column-->
                <div class="col-md-3 offset-md-1">
                    <h5 class="title">Links</h5>
                    <ul>
                        <li><a href="#!">Link 1</a></li>
                        <li><a href="#!">Link 2</a></li>
                        <li><a href="#!">Link 3</a></li>
                        <li><a href="#!">Link 4</a></li>
                    </ul>
                </div>
                <!--/.Second column-->

                <hr class="hidden-md-up">

                <!--Third column-->
                <div class="col-md-3">
                    <h5 class="title">Navigation</h5>
                    <ul>
                        <li><a href="{% url 'main:index' %}">Gymkhana</a></li>
                        <li><a href="#!">Link 2</a></li>
                        <li><a href="#!">Link 3</a></li>
                        <li><a href="#!">Link 4</a></li>
                    </ul>
                </div>
                <!--/.Third column-->

                <hr class="hidden-md-up">

            </div>
        </div>
        <!--/.Footer Links-->

        <hr>
        <!--Social buttons-->
        <div class="social-section">
            <ul>
                <li><a class="btn-floating btn-small btn-fb"><i class="fa fa-facebook"> </i></a></li>
                <li><a class="btn-floating btn-small btn-tw"><i class="fa fa-twitter"> </i></a></li>
                <li><a class="btn-floating btn-small btn-gplus"><i class="fa fa-google-plus"> </i></a></li>
                <li><a class="btn-floating btn-small btn-li"><i class="fa fa-linkedin"> </i></a></li>
                <li><a class="btn-floating btn-small btn-git"><i class="fa fa-github"> </i></a></li>
                <li><a class="btn-floating btn-small btn-pin"><i class="fa fa-pinterest"> </i></a></li>
                <li><a class="btn-floating btn-small btn-ins"><i class="fa fa-instagram"> </i></a></li>
            </ul>
        </div>
        <!--/.Social buttons-->{% endcomment %}
        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © {% now "Y" %} Copyright: <a href="{% url 'forum:index' %}"> Students' Gymkhana WebD Team </a>
            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->
{% endblock %}

<!--Scripts-->
{% block scripts %}
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/tether.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/compiled.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/upvote-toggle.js' %}"></script>
{% endblock %}

{% block customscripts %}
{% endblock %}

{% block navscripts %}
    <script>
        $(".button-collapse").sideNav();
        // Custom scrollbar init
        var el = document.querySelector('.custom-scrollbar');
        Ps.initialize(el);
        // Tooltips Initialization
        $(function () {
            $('[data-toggle="tooltip"]').tooltip({
                'trigger': 'hover'
            })
        });
    </script>
{% endblock %}
</body>
</html>

acac_backend/src/templates/forum/topic_form.html
{% extends 'forum/base.html' %}
{% load staticfiles %}
{% block title %}Add New Topic | {{ block.super }}{% endblock %}
{% block mdbcss %}
    <link rel="stylesheet" href="{% static 'css/mdbadmin.min.css' %}">{% endblock %}
{% block main %}
    <div class="row">
        <!--Form without header-->
        <div class="card">
            <div class="card-block">

                <!--Header-->
                <div>
                    <h3><i class="fa fa-pencil"></i> {% block formtitle %}Post New Topic:{% endblock %}</h3>
                    <hr class="mt-2 mb-2">
                </div>

                <!--Body-->
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <p class="red-text">{{ field.errors }}</p>
                    {% endfor %}
                    <label for="id_category">Category</label>
                    <select class="mdb-select" name="category" id="id_category" required>
                        {% for value, label in form.category.field.choices %}
                            <option value="{{ value }}" {% if topic.category == value %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                    <div class="md-form">
                        {{ form.title }}
                        <label for="{{ form.title.name }}">{{ form.title.label }}</label>
                    </div>
                    <div class="md-form">
                        <div class="chips chips-placeholder"></div>
                        <input type="hidden" name="tags" id="id_tags"/>
                    </div>
                    <div class="md-form">
                        {{ form.content }}
                    </div>
                    <div>
                        {% block updatebutton %}
                            <button class="btn btn-deep-orange" type="submit" value="submit"
                                    onsubmit="return confirm('Are you sure you want to post this?');">Post Topic
                            </button>
                        {% endblock %}
                    </div>
                </form>
            </div>
        </div>
        <!--/Form without header-->
    </div>
{% endblock %}

{% block customscripts %}
    {{ form.media }}
    <script>
        $(document).ready(function () {
            $('.mdb-select').material_select();
        });

        $('.chips-placeholder').material_chip({
            placeholder: 'Enter a tag',
            secondaryPlaceholder: '+Tag',
        });

        $("form").submit(function (e) {
            e.preventDefault();
            var $input = $('.chips-placeholder').material_chip('data');
            var $tags = $input.map(function (elem) {
                return elem.tag;
            }).join(",");
            $('#id_tags').val($tags);
            this.submit();
        });
    </script>
{% endblock %}

acac_backend/src/templates/forum/topic_form_edit.html
{% extends 'forum/topic_form.html' %}
{% block formtitle %}Update Topic:{% endblock %}
{% block updatebutton %}
    <button type="submit" value="submit" class="btn btn-outline-default btn-sm waves-effect" onsubmit="return confirm('Are you sure you want to update this?');">Update</button>
{% endblock %}