acac_backend/src/acac_backend/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.auth.decorators import user_passes_test
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.views.decorators.csrf import csrf_exempt

from acac_backend.schema import PrivateGraphQLView, PublicGraphQLView
from acac_backend.views import FrontendUpdateView, VueView
from oauth.views import SessionView

admin.site.site_title = 'Gymkhana Administration'
admin.site.site_header = 'Gymkhana Administration'
admin.site.index_title = 'Control Panel'

urlpatterns = [
    url(r'^logout/$', LogoutView.as_view(next_page='login'),
        name='logout'),
    url(r'^session/$', SessionView.as_view(), name='session'),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frontend-upload/',
        user_passes_test(lambda u: u.is_superuser, login_url='admin:login')(
            FrontendUpdateView.as_view()),
        name='admin-frontend-upload'),
    path('', include('social_django.urls', namespace='social')),
]

urlpatterns += [
    path("graphql", csrf_exempt(PublicGraphQLView.as_view(graphiql=True))),
    path("pgraphql", csrf_exempt(PrivateGraphQLView.as_view(graphiql=True)))
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'.*', VueView.as_view(), name='vue-js')]

acac_backend/src/konnekt/urls.py
from django.conf.urls import url
from .views import HomeView, SearchView

app_name = 'konnekt'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^search/$', SearchView.as_view(), name='search'),
]

acac_backend/src/main/urls.py
from django.conf.urls import url
from .views import HomeView, BoardView, SocietyView, SenateView, ContactListView, ContactView, OfficeView

app_name = 'main'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^office-bearers/$', OfficeView.as_view(), name='office-bearers'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^contact_list/$', ContactListView.as_view(), name='contact_list'),
    url(r'^board/(?P<slug>[\w-]+)/$', BoardView.as_view(), name='board-detail'),
    url(r'^senate/(?P<slug>[\w-]+)/$', SenateView.as_view(), name='senate-detail'),
    url(r'^society/(?P<slug>[\w-]+)/$', SocietyView.as_view(), name='society-detail'),
]

acac_backend/src/oauth/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView)
from .views import (ProfileDetailView, ProfileEditView, SocialLinkCreateView, SocialLinkUpdateView,
                    SocialLinkDeleteView, RegisterView, AccountActivationView, get_activation_link, SessionView)

app_name = 'oauth'

urlpatterns = [
    url(r'^session/$', SessionView.as_view(), name='session'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^(?P<roll>[\w]+)/get/$', get_activation_link, name='get-act-link'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\']+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        AccountActivationView.as_view(), name='activate'),
    url(r'^sociallink/add/$', SocialLinkCreateView.as_view(), name='link-add'),
    url(r'^(?P<roll>[\w]+)/$', ProfileDetailView.as_view(), name='detail'),
    url(r'^(?P<roll>[\w]+)/edit/$', ProfileEditView.as_view(), name='edit'),
    url(r'sociallink/(?P<username>[\w.-]+)-(?P<social_media>[\w]{2})/$', SocialLinkUpdateView.as_view(),
        name='link-edit'),
    url(r'sociallink/(?P<username>[\w.-]+)-(?P<social_media>[\w]{2})/delete/$', SocialLinkDeleteView.as_view(),
        name='link-delete'),
]

urlpatterns += [
    url(r'^password-reset/$', PasswordResetView.as_view(
        template_name='oauth/password_reset_form.html',
        email_template_name='oauth/mixins/password_reset_email.html',
        subject_template_name='oauth/mixins/password_reset_subject.txt',
        success_url=reverse_lazy('oauth:password_reset_done')
    ), name='password_reset'),
    url(r'^reset/done/$', PasswordResetDoneView.as_view(template_name='oauth/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(
            template_name='oauth/password_reset_confirm.html',
            success_url=reverse_lazy('oauth:password_reset_complete')), name='password_reset_confirm'),
    url(r'^reset/complete/$', PasswordResetCompleteView.as_view(template_name='oauth/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^password-change/$', PasswordChangeView.as_view(
        template_name='oauth/password_change_form.html',
        success_url=reverse_lazy('oauth:password_change_done')), name='password_change'),
    url(r'^password-change/done/$',
        PasswordChangeDoneView.as_view(template_name='oauth/password_change_done.html'), name='password_change_done')
]

acac_backend/src/oauth/models.py
from django.db import models
from django.db.models import Q
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.utils.encoding import force_text
from .tokens import account_activation_token
from versatileimagefield.fields import VersatileImageField
from django.db.models.signals import pre_save


class KonnektQueryset(models.query.QuerySet):
    def search(self, query):
        if query:
            result = self.filter(user__isnull=True)
            for term in query.split():
                if len(term) > 3:
                    result = self.filter(Q(skills__icontains=term) |
                                         Q(user__first_name__icontains=term) |
                                         Q(user__last_name__icontains=term)) | result
                else:
                    result = self.filter(Q(skills__icontains=term)) | result
            return result.distinct().order_by('user__first_name')
        else:
            return self.none()


class UserProfileManager(models.Manager):
    uidb64 = None

    def get_konnekt_queryset(self):
        return KonnektQueryset(self.model, using=self._db)

    def search(self, query):
        return self.get_konnekt_queryset().search(query)

    def _get_user_for_activation(self):
        try:
            uid = force_text(urlsafe_base64_decode(self.uidb64))
            return User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            return None

    def activation_link_valid(self, token=None):
        return account_activation_token.check_token(self._get_user_for_activation(), token)

    def activate_account(self, uidb64=None, token=None):
        self.uidb64 = uidb64
        if self.activation_link_valid(token) and not self._get_user_for_activation().userprofile.email_confirmed:
            user = self._get_user_for_activation()
            user.is_active = True
            user.save()
            user.userprofile.email_confirmed = True
            user.userprofile.save()
        else:
            user = None
        return user


class UserProfile(models.Model):
    # Validators
    valid_year = RegexValidator(r'^[0-9]{4}$', message='Not a valid year!')
    contact = RegexValidator(r'^[0-9]{10}$', message='Not a valid number!')
    # Choices
    PROG_CHOICES = (
        ('BT', 'B.Tech'),
        ('MT', 'M.Tech'),
        ('MSc', 'M.Sc'),
        ('PhD', 'PhD')
    )
    YEAR_CHOICES = (
        # ('0', 'Alumni'),
        ('1', 'First Year'),
        ('2', 'Second Year'),
        ('3', 'Third Year'),
        ('4', 'Fourth Year'),
        ('5', 'Fifth Year')
    )
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('T', 'Transgender')
    )
    BRANCH_CHOICES = (
        ('CSE', 'Computer Science and Engineering'),
        ('AI', ' Artificial Intellingence and Data Science'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CI', ' Civil and Infrastructure Engineering'),
        ('CH', ' Chemichal Engineering'),
        ('MA', 'Mathematics'),
        ('PHY', 'Physics'),
        ('MME', 'Metallurgical and Materials Engineering'),
        ('HSS', 'Humanities and Social Sciences'),
        ('BB', 'Bioscience and Bioengineering'),
        ('SME', ' Management and Entrepreneurship')
    )
    # Database Model
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=True)
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES, default='M')
    roll = models.CharField(max_length=15, unique=True)
    dob = models.DateField()
    prog = models.CharField(
        max_length=5, choices=PROG_CHOICES, verbose_name='programme', default='BT')
    year = models.CharField(max_length=1, choices=YEAR_CHOICES, default='1')
    phone = models.CharField(max_length=10, validators=[contact])
    avatar = VersatileImageField(upload_to='avatar', blank=True, null=True)
    cover = VersatileImageField(upload_to='cover', blank=True, null=True)
    hometown = models.CharField(max_length=128, blank=True, null=True)
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES)
    skills = models.TextField(help_text="Enter your skills, separated by comma.", max_length=1024, blank=True,
                              null=True, default=None)
    about = models.TextField(
        max_length=160, verbose_name='about you', blank=True, null=True)

    class Meta:
        ordering = ["roll"]

    def get_absolute_url(self):
        return reverse('oauth:detail', kwargs={'roll': self.roll})

    objects = UserProfileManager()

    def __str__(self):
        return self.roll + " (" + self.user.get_full_name() + ")"

    @property
    def get_activation_url(self):
        uidb64 = urlsafe_base64_encode(force_bytes(self.user.pk))
        token = account_activation_token.make_token(self.user)
        return reverse('oauth:activate', kwargs={'uidb64': uidb64, 'token': token})

    @property
    def skills_as_list(self):
        if self.skills == '' or not self.skills:
            return ''
        return sorted(self.skills.split(','))


class SocialLink(models.Model):
    SM_CHOICES = (
        ('FB', 'Facebook'),
        ('TW', 'Twitter'),
        ('LI', 'LinkedIn'),
        ('GP', 'Google Plus'),
        ('IG', 'Instagram'),
        ('GH', 'GitHub'),
        ('YT', 'YouTube'),
    )
    FA_CHOICES = (
        ('fa fa-facebook', 'FB'),
        ('fa fa-twitter', 'TW'),
        ('fa fa-linkedin', 'LI'),
        ('fa fa-google-plus', 'GP'),
        ('fa fa-instagram', 'IG'),
        ('fa fa-github', 'GH'),
        ('fa fa-youtube', 'YT'),
    )
    IC_CHOICES = (
        ('fb-ic', 'FB'),
        ('tw-ic', 'TW'),
        ('li-ic', 'LI'),
        ('gplus-ic', 'GP'),
        ('ins-ic', 'IG'),
        ('git-ic', 'GH'),
        ('yt-ic', 'YT'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    social_media = models.CharField(max_length=2, choices=SM_CHOICES)
    link = models.URLField()

    class Meta:
        ordering = ['social_media']

    def get_absolute_url(self):
        return self.user.userprofile.get_absolute_url()

    def __str__(self):
        return self.user.get_full_name() + ' - ' + self.get_social_media_display()

    def get_fai(self):
        for key, value in self.FA_CHOICES:
            if value == self.social_media:
                return key
        return 'fa fa-link'

    def get_sm_ic(self):
        for key, value in self.IC_CHOICES:
            if value == self.social_media:
                return key
        return ''


def topic_pre_save_receiver(sender, instance, *args, **kwargs):
    if instance._state.adding is True:
        name = instance.first_name.split(' ')
        instance.first_name = name[0].title()
        instance.last_name = ' '.join([x.title() for x in name[1:len(name)]])


pre_save.connect(topic_pre_save_receiver, sender=User)

acac_backend/src/oauth/views.py
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, redirect, render, HttpResponseRedirect, reverse
from rest_framework.views import APIView
from .mixins import SocialLinkOwnerMixin
from .models import UserProfile, SocialLink
from .forms import UserProfileUpdateForm, SocialLinkForm, UserProfileForm
from django.urls import reverse_lazy


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = UserProfile
    template_name = 'oauth/profile_detail.html'

    def get_object(self, queryset=None):
        roll = self.kwargs.get('roll')
        return get_object_or_404(UserProfile, roll=roll.upper(), email_confirmed=True)

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        context['social_media_count'] = len(SocialLink.SM_CHOICES)
        return context


class ProfileEditView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    template_name = 'oauth/profile_edit.html'
    form_class = UserProfileUpdateForm

    def get_object(self, queryset=None):
        roll = self.kwargs.get('roll')
        return get_object_or_404(UserProfile, roll=roll.upper(), email_confirmed=True)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.id != self.get_object().user.id:
            raise PermissionDenied
        return super(ProfileEditView, self).dispatch(request, *args, **kwargs)


class SocialLinkCreateView(LoginRequiredMixin, CreateView):
    model = SocialLink
    template_name = 'oauth/sociallink_create.html'
    form_class = SocialLinkForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(SocialLinkCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(SocialLinkCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class SocialLinkUpdateView(SocialLinkOwnerMixin, UpdateView):
    model = SocialLink
    template_name = 'oauth/sociallink_update.html'
    form_class = SocialLinkForm

    def get_object(self, queryset=None):
        user = self.kwargs.get('username')
        social_media = self.kwargs.get('social_media')  # gets social_media value from url
        return get_object_or_404(SocialLink, user__username=user, social_media=social_media)


class SocialLinkDeleteView(SocialLinkOwnerMixin, DeleteView):
    model = SocialLink

    def get_success_url(self):
        return self.request.user.userprofile.get_absolute_url()

    def get_object(self, queryset=None):
        user = self.kwargs.get('username')
        social_media = self.kwargs.get('social_media')  # gets social_media value from url
        return get_object_or_404(SocialLink, user__username=user, social_media=social_media)


class RegisterView(LoginRequiredMixin, CreateView):
    template_name = 'oauth/register.html'
    success_url = reverse_lazy('forum:index')
    form_class = UserProfileForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        response_redirect = super(RegisterView, self).form_valid(form)
        return response_redirect

    def dispatch(self, request, *args, **kwargs):
        if hasattr(self.request.user, 'userprofile'):
            return HttpResponseRedirect(reverse('oauth:detail', kwargs={'roll': self.request.user.userprofile.roll}))
        else:
            return super().dispatch(request, args, kwargs)


class AccountActivationView(RedirectView):
    def get(self, request, uidb64=None, token=None, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        activated_user = UserProfile.objects.activate_account(uidb64=uidb64, token=token)

        if activated_user:
            return redirect(activated_user.userprofile.get_absolute_url())
        else:
            # invalid link
            return render(self.request, 'oauth/invalid_activation.html')


def get_activation_link(request, roll):
    userprofile = UserProfile.objects.get(roll=roll.upper())
    return render(request, 'oauth/account_activation_email.html', {'user': userprofile.user})


class SessionView(LoginRequiredMixin, APIView):
    def get(self, request, *args, **kwargs):
        key = self.request.user.social_auth.get(provider="google-oauth2").extra_data['access_token']
        response = HttpResponseRedirect("/login?key=" + key)
        return response

acac_backend/src/templates/oauth/account_activation_email.html
{% extends 'main/base.html' %}
{% block title %}Activate account for {{ user.username }}{% endblock %}
{% block main %}
    <div style="height: 100vh">
        <div class="flex-center flex-column text-center">
            <h1 class="animated fadeIn mb-2">Hi {{ user.username }},</h1>
            <h5 class="animated fadeIn mb-1">Please click on the link below to confirm your registration:</h5>
            <h5 class="animated fadeIn mb-1 blue-text"><a href="{{ user.userprofile.get_activation_url }}"
                                                          class="btn btn-lg btn-secondary" role="button">Activate</a>
            </h5>
        </div>
    </div>
{% endblock %}
{% block footer %}{% endblock %}

acac_backend/src/templates/oauth/invalid_activation.html
{% extends 'main/base.html' %}

{% block main %}
    <div class="mt-5">
        <h2 class="text-center">Invalid Account Activation Link</h2>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

acac_backend/src/templates/oauth/password_change_done.html
{% extends "main/base.html" %}
{% block title %}Password change successful | {{ block.super }}{% endblock %}
{% block customstyles %}
    <style>
        .container.view {
            height: 100vh;
        }
    </style>
{% endblock %}
{% block main %}
    <div class="container view">
        <div class="flex-center flex-column text-center">
            <h1 class="h1-responsive animated fadeIn mb-3">Password change successful!</h1>
            <a href="{% url 'login' %}" class="btn btn-large blue animated fadeIn"><i class="fa fa-sign-in mr-2"></i>
                Dashboard</a>
        </div>
    </div>
{% endblock %}

acac_backend/src/templates/oauth/password_reset_complete.html
{% extends "main/base.html" %}
{% block title %}Password reset complete | {{ block.super }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block customstyles %}
    <style>
        html, body, .view {
            height: 100vh;
        }
    </style>
{% endblock %}
{% block main %}
        <div class="container view">
            <div class="flex-center flex-column text-center">
                <h1 class="h1-responsive animated fadeIn mb-2">Password reset complete!</h1>
                <h5 class="animated fadeIn mb-1">Your new password has been set.  You may go ahead and log in now.</h5>
                <a href="{% url 'login' %}" class="btn btn-large blue animated fadeIn"><i
                        class="fa fa-sign-in mr-2"></i>
                    Login</a>
            </div>
        </div>
{% endblock %}

acac_backend/src/templates/oauth/password_reset_done.html
{% extends "main/base.html" %}
{% block title %}Password reset sent | {{ block.super }}{% endblock %}
{% block customstyles %}
    <style>
        .container.view {
            height: 100vh;
        }
    </style>
{% endblock %}
{% block main %}
    <div class="container view">
        <div class="flex-center flex-column text-center">
            <h1 class="h1-responsive animated fadeIn mb-2">Password reset link sent!</h1>
            <h5 class="animated fadeIn mb-1">We've emailed you instructions for setting your password, if an account
                exists with the email you entered. You should receive them shortly.</h5>
            <h5 class="animated fadeIn mb-1">If you don't receive an email, please make sure you've entered the address
                you registered with, and check your spam folder.</h5>
            <a href="{% url 'login' %}" class="btn btn-large blue animated fadeIn"><i class="fa fa-sign-in mr-2"></i>
                Login</a>
        </div>
    </div>
{% endblock %}

acac_backend/src/templates/oauth/profile_detail.html
{% extends 'forum/base.html' %}
{% load staticfiles %}
{% block title %}Profile: {{ userprofile.user.get_full_name }}{% endblock %}
{% block customstyles %}
    <link rel="stylesheet" href="{% static 'css/profile_detail.css' %}"/>
    <style>
        .fixed-action-btn-fix {
            position: fixed;
            right: 24px;
            bottom: 35px;
            padding-top: 15px;
            margin-bottom: 0;
            z-index: 998;
        }

        .card-up {
            background: url('{% include 'oauth/mixins/user_cover_src_mixin.html' with userprofile=userprofile %}') center;
            background-size: cover;
        }

        .d-flex.justify-content-between.align-middle {
            margin: 0 !important;
        }

        .align-middle div#edit i {
            font-size: 1.4rem;
        }
    </style>
{% endblock %}
{% block navtitle %}About: {{ userprofile.user.first_name }}{% endblock %}
{% block content %}
    <div class="profile-container">
        {% if request.user.id == userprofile.user.id %}
            <div class="fixed-action-btn-fix">
                <a class="btn-floating btn-large red" href="{% url 'oauth:edit' userprofile.roll %}" data-toggle="tooltip"
                   data-placement="left" title="Edit Profile">
                    <i class="fa fa-pencil"></i>
                </a>
            </div>
        {% endif %}
        <div class="rellax header" data-rellax-speed="-4">
            <div class="flex-center">
                <h2 class="h2-responsive white-text"><strong>Gymkhana</strong> About Me</h2>
            </div>
        </div>
        <div class="rellax content" data-rellax-speed="5">
            <div class="container-fluid">
                <div class="row text-center">
                    <!--First column-->
                    <div class="col-12">
                        <!--Rotating card-->
                        <div class="card-wrapper">
                            <div id="card-1">
                                <div class="face front">
                                    <!-- Image-->
                                    <div class="card-up">
                                    </div>
                                    <!--Avatar-->
                                    <div class="avatar"><img
                                            src="{% if userprofile.avatar %}{{ userprofile.avatar.crop.150x150 }}{% else %}{% static 'assets/others/missing.png' %}{% endif %}"
                                            class="rounded-circle img-responsive">
                                    </div>
                                    <!--Content-->
                                    <div class="card-block">
                                        <h4>{{ userprofile.user.get_full_name }}</h4>
                                        <span> ({{ userprofile.roll }})</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/.Rotating card-->
                    </div>
                    <!--/First column-->
                </div>
            </div>
            <div class="container-fluid mt-1 mb-1">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card card-block">
                                <h4 class="flex-item card-title">Personal Info</h4>
                                <div id="hr"></div>
                                <div id="icons" class="flex-column">
                                    <div><i class="fa fa-venus-mars"></i>
                                        <span>{{ userprofile.get_gender_display }}</span>
                                    </div>
                                    <div><i class="fa fa-phone"></i>
                                        <span>{{ userprofile.phone }}</span>
                                    </div>
                                    <div><i class="fa fa-envelope-o"></i>
                                        <span>{{ userprofile.user.email }}</span>
                                    </div>
                                    <div><i class="fa fa-map-marker"></i>
                                        <span>{{ userprofile.hometown }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card card-block">
                                <h4 class="card-title">Branch, date of birth and more</h4>
                                <div id="hr"></div>
                                <div id="icons" class="flex-column">
                                    <div><i class="fa fa-birthday-cake"></i>
                                        <span>{{ userprofile.dob }}</span>
                                    </div>
                                    <div><i class="fa fa-drivers-license-o"></i>
                                        <span>{{ userprofile.get_prog_display }}</span>
                                    </div>
                                    <div><i class="fa fa-graduation-cap"></i>
                                        <span>{{ userprofile.get_branch_display }}</span>
                                    </div>
                                    <div><i class="fa fa-calendar-o"></i>
                                        <span>{{ userprofile.get_year_display }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card card-block">
                                <h4 class="card-title">Skills</h4>
                                <div id="hr"></div>
                                <div class="flex-column">
                                    {% if not userprofile.skills_as_list %}
                                        <small>Not yet added!</small>
                                    {% else %}
                                        <h4 class="d-flex flex-wrap">
                                            {% for skill in userprofile.skills_as_list %}
                                                <span class="chip"><a
                                                        href="{% url 'konnekt:search' %}?q={{ skill|urlencode }}">{{ skill }}</a></span>
                                            {% endfor %}
                                        </h4>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card card-block">
                                <h4 class="card-title">About</h4>
                                <div id="hr"></div>
                                {% if not userprofile.about %}
                                    <small>Not yet added!</small>
                                {% else %}
                                    <div class="text-center" style="word-wrap: break-word">
                                        {{ userprofile.about|linebreaks }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card card-block">
                                <div class="d-flex justify-content-between">
                                    <h4 class="card-title">Social Links</h4>
                                    {% if request.user.id == userprofile.user.id %}
                                        {% if not social_media_count == userprofile.user.sociallink_set.all.count %}
                                            <a href="{% url 'oauth:link-add' %}" data-toggle="tooltip"
                                               data-placement="left"
                                               title="Add Social Link"><i class="fa fa-plus text-primary"></i></a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                                <div id="hr"></div>
                                <div id="icons" class="flex-column">
                                    {% if not userprofile.user.sociallink_set.all %}
                                        <small>Not yet added!</small>
                                    {% else %}
                                        {% for link in userprofile.user.sociallink_set.all %}
                                            <div class="d-flex justify-content-between align-middle">
                                                <div style="word-wrap: break-word"><i class="fa {{ link.get_fai }}"></i>
                                                    <span>{{ link.link|urlizetrunc:36 }}</span>
                                                </div>
                                                {% if request.user.id == userprofile.user.id %}
                                                    {% if not social_media_count == userprofile.user.sociallink_set.all.count %}
                                                        <div id="edit" class="align-middle">
                                                            <a href="{% url 'oauth:link-edit' request.user.username link.social_media %}"
                                                               data-toggle="tooltip" data-placement="left"
                                                               title="Edit {{ link.get_social_media_display }} Link"><i
                                                                    class="fa fa-pencil"></i></a>
                                                        </div>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block customscripts %}
    <script src="{% static 'js/rellax.min.js' %}"></script>
    <script>
        var rellax = new Rellax('.rellax');
    </script>
{% endblock %}

{% block footer %}{% endblock %}