acac_backend/src/acac_backend/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.auth.decorators import user_passes_test
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.views.decorators.csrf import csrf_exempt

from acac_backend.schema import PrivateGraphQLView, PublicGraphQLView
from acac_backend.views import FrontendUpdateView, VueView
from oauth.views import SessionView

admin.site.site_title = 'Gymkhana Administration'
admin.site.site_header = 'Gymkhana Administration'
admin.site.index_title = 'Control Panel'

urlpatterns = [
    url(r'^logout/$', LogoutView.as_view(next_page='login'),
        name='logout'),
    url(r'^session/$', SessionView.as_view(), name='session'),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frontend-upload/',
        user_passes_test(lambda u: u.is_superuser, login_url='admin:login')(
            FrontendUpdateView.as_view()),
        name='admin-frontend-upload'),
    path('', include('social_django.urls', namespace='social')),
]

urlpatterns += [
    path("graphql", csrf_exempt(PublicGraphQLView.as_view(graphiql=True))),
    path("pgraphql", csrf_exempt(PrivateGraphQLView.as_view(graphiql=True)))
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'.*', VueView.as_view(), name='vue-js')]

acac_backend/src/forum/urls.py
from django.conf.urls import url
from forum import views

app_name = 'forum'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^answered-by-me/$', views.AnswerView.as_view(), name='answered-by-user'),
    url(r'^topic/add/$', views.TopicCreateView.as_view(), name='add_topic'),
    url(r'^(?P<slug>[\w-]+)/$', views.TopicDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/update/$', views.TopicUpdateView.as_view(), name='update_topic'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.TopicDeleteView.as_view(), name='delete_topic'),
    url(r'^answer/(?P<pk>\d+)/delete/$', views.AnswerDeleteView.as_view(), name='delete_answer'),
    url(r'^test/$', views.test, name='test'),
]

acac_backend/src/main/urls.py
from django.conf.urls import url
from .views import HomeView, BoardView, SocietyView, SenateView, ContactListView, ContactView, OfficeView

app_name = 'main'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^office-bearers/$', OfficeView.as_view(), name='office-bearers'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^contact_list/$', ContactListView.as_view(), name='contact_list'),
    url(r'^board/(?P<slug>[\w-]+)/$', BoardView.as_view(), name='board-detail'),
    url(r'^senate/(?P<slug>[\w-]+)/$', SenateView.as_view(), name='senate-detail'),
    url(r'^society/(?P<slug>[\w-]+)/$', SocietyView.as_view(), name='society-detail'),
]

acac_backend/src/events/models.py
from django.db import models
from main.models import Society


class Event(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    location = models.CharField(max_length=64)
    date = models.DateTimeField()
    society = models.ForeignKey(Society, null=True, blank=True, default=None, on_delete=models.CASCADE,
                             help_text="Leave blank to make this a general event.")
    published = models.BooleanField(default=True)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.name

acac_backend/src/main/models.py
import datetime
from django.db import models
from django.core.validators import RegexValidator
from oauth.models import UserProfile
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from versatileimagefield.fields import VersatileImageField
from photologue.models import Gallery

YEAR_CHOICES = []
for r in range(2008, (datetime.datetime.now().year + 2)):
    YEAR_CHOICES.append((str(r), r))

SKIN_CHOICES = (
    ('white-skin', 'White'),
    ('black-skin', 'Black'),
    ('cyan-skin', 'Cyan'),
    ('mdb-skin', 'MDB'),
    ('deep-purple-skin', 'Deep Purple'),
    ('navy-blue-skin', 'Navy Blue'),
    ('pink-skin', 'Pink'),
    ('indigo-skin', 'Indigo'),
    ('light-blue-skin', 'Light Blue'),
    ('grey-skin', 'Grey'),
)


class Faculty(models.Model):
    #validators
    contact = RegexValidator(r'^[0-9]{10}$', message='Not a valid number!')
    # Database Model
    name = models.CharField(max_length=128)
    email = models.EmailField(default=None)
    cover = VersatileImageField(upload_to='cover', blank=True, null=True)
    avatar = VersatileImageField(upload_to='avatar',blank=True, null=True)
    phone = models.CharField(max_length=10, validators=[contact])

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Faculty"

    def __str__(self):
        return self.name


class Board(models.Model):
    # Validators
    valid_year = RegexValidator(r'^[0-9]{4}$', message='Not a valid year!')
    # Model
    name = models.CharField(max_length=128)
    description = RichTextUploadingField(blank=True)
    cover = VersatileImageField('Cover', upload_to='board_%Y', help_text="Upload high quality picture")
    skin = models.CharField(max_length=32, choices=SKIN_CHOICES, blank=True, default='mdb-skin',
                            help_text="Choose a skin while displaying board page.")
    secretary = models.ForeignKey(UserProfile, related_name='secy',
                                        limit_choices_to={'user__is_staff': True}, null=True, blank=True,
                                        on_delete=models.SET_NULL)
    vice_president = models.ForeignKey(UserProfile, related_name='vice_president',
                                        limit_choices_to={'user__is_staff': True}, null=True, blank=True,
                                        on_delete=models.SET_NULL)
    president = models.ForeignKey(Faculty, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    report_link = models.URLField(help_text='Add a drive link to show on board page', null=True, blank=True)
    constitution_link = models.URLField(help_text='Add a drive link of the Constitution to show on board page', null=True, blank=True)
    gallery = models.ForeignKey(Gallery, blank=True, null=True, on_delete=models.SET_NULL,
                                help_text="Select a carousel gallery to link to this board.")
    custom_html = models.TextField(blank=True, null=True, default=None,
                                   help_text="Add custom HTML to view on board page.")
    slug = models.SlugField(unique=True, help_text="This will be used as URL. /board/slug")
    is_active = models.BooleanField(default=False)
    year = models.CharField(max_length=4, choices=YEAR_CHOICES, validators=[valid_year])

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Boards"

    def get_absolute_url(self):
        return reverse('main:board-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name + " - " + str(self.year)


class Society(models.Model):
    # Choices
    TYPE_CHOICES = (
        ('S', 'Society'),
        ('T', 'Team'),
    )
    # Model
    name = models.CharField(max_length=128)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    stype = models.CharField(max_length=1, choices=TYPE_CHOICES, default='S', help_text="Specify type as Society or Team.",
                             verbose_name="Type")
    description = RichTextUploadingField(blank=True)
    cover = VersatileImageField(upload_to='society_%Y', blank=True, null=True,
                                help_text="Upload high quality picture")
    skin = models.CharField(max_length=32, choices=SKIN_CHOICES, blank=True, default='mdb-skin',
                            help_text="Choose a skin while displaying society page.")
    student_coordinators = models.ManyToManyField(UserProfile, related_name='student_coordinator',
                                           limit_choices_to={'user__is_staff': True},
                                           blank=True, default=None,help_text="Select all the Student Coordinators of this society. ")
    core_members = models.ManyToManyField(UserProfile, blank=True)
    gallery = models.ForeignKey(Gallery, blank=True, null=True, on_delete=models.SET_NULL,
                                help_text="Select a gallery to link to this society.")
    resources_link = models.URLField(blank=True, null=True, default=None)
    custom_html = models.TextField(blank=True, null=True, default=None,
                                   help_text="Add custom HTML to view on club page.")
    slug = models.SlugField(unique=True, help_text="This will be used as URL. /society/slug")
    published = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Societies"

    @property
    def year(self):
        return self.board.year

    @property
    def is_active(self):
        return self.board.is_active

    def get_absolute_url(self):
        return reverse('main:soc-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name + " - " + str(self.year)


class Activity(models.Model):
    name = models.CharField(max_length=64)
    society = models.ForeignKey(Society, on_delete=models.CASCADE)
    description = RichTextUploadingField()
    custom_html = models.TextField(blank=True, null=True, default=None)

    class Meta:
        verbose_name_plural = 'Activities'

    def get_absolute_url(self):  # pragma: no use
        return reverse('main:activity-gallery', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' - ' + self.society.name


class Senate(models.Model):
    # Validators
    valid_year = RegexValidator(r'^[0-9]{4}$', message='Not a valid year!')
    # Model
    name = models.CharField(max_length=128)
    description = RichTextUploadingField(blank=True)
    cover = VersatileImageField('Cover', upload_to='society_%Y', help_text="Upload high quality picture")
    skin = models.CharField(max_length=32, choices=SKIN_CHOICES, blank=True, default='mdb-skin',
                            help_text="Choose a skin while displaying senate page.")
    gen_secy_senate = models.ForeignKey(UserProfile, related_name='gen_secy_senate', limit_choices_to={'user__is_staff': True},
                                null=True, blank=True, on_delete=models.SET_NULL)
    gen_secy_acac = models.ForeignKey(UserProfile, related_name='gen_secy_acac', limit_choices_to={'user__is_staff': True},
                                null=True, blank=True, on_delete=models.SET_NULL)
    report_link = models.URLField(help_text='Add a drive link to show on board page', null=True, blank=True)
    constitution_link = models.URLField(help_text='Add a drive link of constitution to show on board page', null=True, blank=True)
    custom_html = models.TextField(blank=True, null=True, default=None,
                                   help_text="Add custom HTML to view on board page.")
    slug = models.SlugField(unique=True, help_text="This will be used as URL. /senate/slug")
    is_active = models.BooleanField(default=False)
    year = models.CharField(max_length=4, choices=YEAR_CHOICES, validators=[valid_year])

    class Meta:
        ordering = ["-id"]

    def get_absolute_url(self):
        return reverse('main:senate-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name + ' - ' + self.year


class SenateMembership(models.Model):
    ROLE_CHOICES = (
        ('SECY', 'Student Secretary'),
        ('SER', 'Student Elected Representative'),
    )
    P_YEAR_CHOICES = (
        ('1', 'First Year'),
        ('2', 'Second Year'),
        ('3', 'Third Year'),
        ('4', 'Fourth Year'),
    )
    senate = models.ForeignKey(Senate, on_delete=models.CASCADE)
    userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    role = models.CharField(max_length=5, choices=ROLE_CHOICES)
    year = models.CharField(max_length=1, choices=P_YEAR_CHOICES)

    def __str__(self):
        return self.userprofile.user.get_full_name()


class SocialLink(models.Model):
    SM_CHOICES = (
        ('FB', 'Facebook'),
        ('TW', 'Twitter'),
        ('LI', 'LinkedIn'),
        ('GP', 'Google Plus'),
        ('IG', 'Instagram'),
        ('GH', 'GitHub'),
        ('YT', 'YouTube'),
    )
    FA_CHOICES = (
        ('fa fa-facebook', 'FB'),
        ('fa fa-twitter', 'TW'),
        ('fa fa-linkedin', 'LI'),
        ('fa fa-google-plus', 'GP'),
        ('fa fa-instagram', 'IG'),
        ('fa fa-github', 'GH'),
        ('fa fa-youtube', 'YT'),
    )
    IC_CHOICES = (
        ('fb-ic', 'FB'),
        ('tw-ic', 'TW'),
        ('li-ic', 'LI'),
        ('gplus-ic', 'GP'),
        ('ins-ic', 'IG'),
        ('git-ic', 'GH'),
        ('yt-ic', 'YT'),
    )
    society = models.ForeignKey(Society, on_delete=models.CASCADE)
    social_media = models.CharField(max_length=2, choices=SM_CHOICES)
    link = models.URLField()

    class Meta:
        ordering = ['social_media']

    def __str__(self):
        return self.society.name + ' - ' + self.get_social_media_display()

    def get_fai(self):
        for key, value in self.FA_CHOICES:
            if value == self.social_media:
                return key
        return 'fa fa-link'

    def get_sm_ic(self):
        for key, value in self.IC_CHOICES:
            if value == self.social_media:

acac_backend/src/news/models.py
from django.db import models
from oauth.models import UserProfile
from main.models import Society
from ckeditor_uploader.fields import RichTextUploadingField
from versatileimagefield.fields import VersatileImageField


class News(models.Model):
    title = models.CharField(max_length=128)
    cover = VersatileImageField(upload_to='news_%Y', blank=True, null=True,
                                help_text="Upload high quality image to use as cover photo.")
    author = models.ForeignKey(UserProfile, null=True, on_delete=models.SET_NULL)
    content = RichTextUploadingField()
    society = models.ForeignKey(Society, blank=True, null=True, on_delete=models.CASCADE, default=None,
                             help_text="Leave blank to make this a general news.")
    date = models.DateField(editable=True)

    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'news'

    def __str__(self):
        return self.title


class Update(models.Model):
    title = models.CharField(max_length=128)
    content = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

acac_backend/src/main/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'length': '10'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'length': '128'}))

    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'subject', 'message']

acac_backend/src/templates/main/base.html
{% load staticfiles %}
{% load linkactive %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block metatags %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% endblock %}
    {% block custommeta %}
    {% endblock %}
    <title>{% block title %}Students' Gymkhana - IIT Jodhpur{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block mdbcss %}
        <link rel="stylesheet" href="{% static 'css/compiled.min.css' %}">{% endblock %}
    <link rel="icon" href="{% static 'assets/default-favicon.ico' %}">
    {% block customstyles %}
    {% endblock %}
</head>

<body class="{% block skin %}mdb-skin{% endblock %}">
<!--Header-->
{% block header %}
    <header>
        <!--Navbar-->
        {% block navbar %}
            <nav class="navbar fixed-top navbar-toggleable-md navbar-dark">
                <div class="container">
                    <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse"
                            data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'main:index' %}">
                        <img src="{% static 'assets/favicon.png' %}" alt="logo" style="height: 2.2rem;width: auto;">
                    </a>
                    <div class="navbar-collapse collapse" id="navbarNav" aria-expanded="false">
                        <!--Links-->
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link waves-effect waves-light" href="{% url 'main:index' %}">Home</a>
                            </li>
                            <li class="nav-item dropdown{% active '/society/' %}">
                                <a class="nav-link dropdown-toggle waves-effect waves-light" href="#"
                                   id="navbarDropdownMenuLink"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Societies
                                </a>
                                <div class="dropdown-menu dropdown-dark" aria-labelledby="navbarDropdownMenuLink">
                                    {% for society in society_link_list %}
                                        <a class="dropdown-item waves-effect waves-light "
                                           href="{{ society.get_absolute_url }}">{{ society.name }}</a>
                                    {% endfor %}
                                    <a class="dropdown-item waves-effect waves-light "
                                       href="{{ senate.get_absolute_url }}">{{ senate.name }}</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link waves-effect waves-light" href="{% url 'forum:index' %}">Forum</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link waves-effect waves-light" href="{% url 'main:office-bearers' %}">People</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!--Navbar-->
        {% endblock %}
    </header>
{% endblock %}

{% block fullpagecontent %}
{% endblock %}

<main>
    {% block main %}
    {% endblock %}
</main>
<!--Footer-->
{% block footer %}
    <footer class="page-footer mt-0">
        <!--Footer Links-->
        <div class="container wow fadeIn" data-wow-delay="0.3s">
            <div class="row">
                <!--First column-->
                <div class="col-md-6">
                    <h5 class="title">About Us</h5>
                    <p>Student Gymkhana IITJ </p>
                    <p>Coming Soon!</p>
                </div>
                <!--/.First column-->
                <!--Second column-->
                <div class="col-md-3 ml-auto text-md-right">
                    <h5 class="title">Quick Links</h5>
                    <ul>
                        <li><a href="http://iitj.ac.in" target="_blank" style="opacity: 0.6">IIT Jodhpur</a></li>
                        <li><a href="{% url 'main:contact' %}" style="opacity: 0.6">Contact Us</a></li>
                        <li><a href="http://iitj.ac.in/academics/index.php?id=academic_calendar" style="opacity: 0.6">Acadmic Calender</a></li>
                    </ul>
                </div>
                <!--/.Second column-->
            </div>
        </div>
        <!--/.Footer Links-->
        <hr>
        <!--Social buttons-->
        <div class="social-section">
            <h4 class="h4-responsive">Follow us </h4>
            <ul>
                <li><a href="https://www.flickr.com/photos/134892933@N08" target="_blank"
                       class="btn-floating btn-small btn-tw wow fadeInUp" data-wow-delay="0.2s">
                    <i class="fa fa-flickr"> </i></a>
                </li>
            </ul>
        </div>
        <!--/.Social buttons-->
        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © {% now "Y" %} Copyright: <a href="#"> Students' Gymkhana WebD Team </a>

            </div>
        </div>
        <!--/.Copyright-->
    </footer>
    <!--/.Footer-->
{% endblock %}

{% block scripts %}
    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="/static/js/jquery-3.1.1.min.js"></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="/static/js/tether.min.js"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="/static/js/compiled.min.js"></script>

    <script>
        $("blockquote").addClass("blockquote");
        $('div#description').find('img').addClass('img-fluid');
    </script>
{% endblock %}

{% block customscripts %}
{% endblock %}

</body>
</html>

acac_backend/src/templates/main/club.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title %}{{ club.name }} | {{ block.super }}{% endblock %}
{% block skin %}{{ club.skin|default:block.super }}{% endblock %}
{% block customstyles %}
    <link rel="stylesheet" href="{% static 'css/club_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/news_event.css' %}"/>
    {% if club.cover %}
        <style>
            @media (max-width: 415px) {
                .society-photo {
                    height: 20rem !important;
                    background: url("{{ club.cover.crop.450x420 }}") no-repeat center !important;
                    background-size: cover !important;
                    -webkit-background-size: cover !important;
                }
            }

            @media (min-width: 416px) and (max-width: 1000px) {
                .society-photo {
                    height: 23rem !important;
                    background: url("{{ club.cover.crop.1280x900 }}");
                    background-repeat: no-repeat !important;
                    background-size: cover !important;
                    -webkit-background-size: cover !important;
                }
            }

            @media (min-width: 1001px) {
                .society-photo {
                    height: 28rem !important;
                    background: url("{{ club.cover.crop.1440x750 }}");
                    background-repeat: no-repeat !important;
                    background-size: cover !important;
                    -webkit-background-size: cover !important;
                }
            }
        </style>
    {% endif %}
{% endblock %}
{% block main %}
    <div class="streak streak-lg streak-photo society-photo view hm-black-light">
        <div class="mask flex-center">
            <div class="flex-center text-white">
                <ul>
                    <li><h1 class="h1-responsive wow fadeIn"><b>{{ club.name }}</b></h1></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="streak-edge-header card z-depth-1-half">
        <div class="col-md-12">
            <h2 class="h2-responsive mb-2">About</h2>
            <div id="description">{{ club.description|safe }}</div>
            {% if club.resources_link %}
                <div class="float-right">
                    <small>Link to resources</small>
                    <a href="{{ club.resources_link }}" target="_blank" role="button" class="btn btn-secondary"><i
                            class="fa fa-external-link"></i></a>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="container mt-2">
        <div class="row mb-2">
            <div class="col-md-4 mt-2">
                {% include 'main/mixins/event_list_module.html' with event_list=event_list %}
            </div>
            <div class="col-md-8 mt-1">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs tabs-2 primary-color" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#panel1" role="tab">Activities</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#panel2" role="tab">News</a>
                    </li>
                </ul>
                <!-- Tab panels -->
                <div class="tab-content card-block">
                    <div class="tab-pane fade in show active" id="panel1" role="tabpanel">
                        <br>
                        {% include 'main/mixins/activity_list_module.html' with activity_list=activity_list %}
                    </div>
                    <div class="tab-pane fade pl-md-4 pr-md-4" id="panel2" role="tabpanel">
                        <br>
                        {% include 'main/mixins/news_list_club_module.html' with news_list=news_list %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'main/mixins/event_modal_mixin.html' with event_list=event_list %}
    {% include 'main/mixins/news_modal_mixin.html' with news_list=news_list %}
    <div class="container mt-1">
        <div class="row flex-center">
            <div class="col-sm-10">
                <!--Card Primary-->
                <div class="card primary-color text-center z-depth-2 mt-2 mb-2">
                    <div class="card-block">
                        <h3 class="h3-responsive white-text mb-0">Key People</h3>
                    </div>
                </div>
                <!--/.Card Primary-->
            </div>
        </div>
    </div>
    <div class="container section team-section">
        <div class="row flex-center">
            {% include 'main/mixins/club_user_round_card_mixin.html' with userprofile=club.captain designation='Captain' %}
            {% if club.vice_captain_one %}
                {% include 'main/mixins/club_user_round_card_mixin.html' with userprofile=club.vice_captain_one designation='Vice Captain' %}
            {% endif %}
            {% if club.vice_captain_two %}
                {% include 'main/mixins/club_user_round_card_mixin.html' with userprofile=club.vice_captain_two designation='Vice Captain' %}
            {% endif %}
           {% if club.vice_captain_three %}
                {% include 'main/mixins/club_user_round_card_mixin.html' with userprofile=club.vice_captain_three designation='Vice Captain' %}
            {% endif %}
            {% if club.mentor %}
                {% include 'main/mixins/club_user_round_card_mixin.html' with userprofile=club.mentor designation='Mentor' %}
            {% endif %}
        </div>
    </div>
    {% if club.gallery %}
        <div class="container">
            <div class="row flex-center">
                <div class="col-sm-10">
                    <!--Card Primary-->
                    <div class="card primary-color text-center z-depth-2 mt-2 mb-2">
                        <div class="card-block">
                            <h3 class="h3-responsive white-text mb-0">Gallery</h3>
                        </div>
                    </div>
                    <!--/.Card Primary-->
                </div>
            </div>
        </div>
        <div id="mdb-lightbox-ui"></div>
        <div class="container-fluid">
            <div class="row mt-1 mb-2">
                {% include 'main/mixins/club_gallery_mixin.html' with gallery=club.gallery %}
            </div>
        </div>
    {% endif %}
    {% if club.custom_html %}
        {{ club.custom_html|safe }}
    {% endif %}
    {% if member_list %}
        <div class="container">
            <div class="row flex-center">
                <div class="col-sm-10">
                    <!--Card Primary-->
                    <div class="card primary-color text-center z-depth-2 mt-2 mb-2">
                        <div class="card-block">
                            <h3 class="h3-responsive white-text mb-0">Volunteers</h3>
                        </div>
                    </div>
                    <!--/.Card Primary-->
                </div>
            </div>
        </div>
        <section class="container-fluid section team-section">
            <!--First row-->
            <div class="row flex-center mt-3 center-on-small-only">
                {% for member in member_list %}
                    {% include 'main/mixins/club_member_card_mixin.html' with userprofile=member %}
                {% endfor %}
            </div>
            <!--/Second row-->
        </section>
    {% endif %}

{% endblock %}

{% block customscripts %}
    <script>
        new WOW().init();
        // MDB Lightbox Init
        $(function () {
            $("#mdb-lightbox-ui").load("/static/mdb-addons/mdb-lightbox-ui.html");
        });

        $(document).ready(function () {
            $('#carousel-gallery').hammer().on('swipeleft', function () {
                $(this).carousel('next');
            })
            $('#carousel-gallery').hammer().on('swiperight', function () {
                $(this).carousel('prev');
            })
        });
    </script>
{% endblock %}