acac_backend/src/acac_backend/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.auth.decorators import user_passes_test
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.views.decorators.csrf import csrf_exempt

from acac_backend.schema import PrivateGraphQLView, PublicGraphQLView
from acac_backend.views import FrontendUpdateView, VueView
from oauth.views import SessionView

admin.site.site_title = 'Gymkhana Administration'
admin.site.site_header = 'Gymkhana Administration'
admin.site.index_title = 'Control Panel'

urlpatterns = [
    url(r'^logout/$', LogoutView.as_view(next_page='login'),
        name='logout'),
    url(r'^session/$', SessionView.as_view(), name='session'),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frontend-upload/',
        user_passes_test(lambda u: u.is_superuser, login_url='admin:login')(
            FrontendUpdateView.as_view()),
        name='admin-frontend-upload'),
    path('', include('social_django.urls', namespace='social')),
]

urlpatterns += [
    path("graphql", csrf_exempt(PublicGraphQLView.as_view(graphiql=True))),
    path("pgraphql", csrf_exempt(PrivateGraphQLView.as_view(graphiql=True)))
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'.*', VueView.as_view(), name='vue-js')]

acac_backend/src/main/urls.py
from django.conf.urls import url
from .views import HomeView, BoardView, SocietyView, SenateView, ContactListView, ContactView, OfficeView

app_name = 'main'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^office-bearers/$', OfficeView.as_view(), name='office-bearers'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^contact_list/$', ContactListView.as_view(), name='contact_list'),
    url(r'^board/(?P<slug>[\w-]+)/$', BoardView.as_view(), name='board-detail'),
    url(r'^senate/(?P<slug>[\w-]+)/$', SenateView.as_view(), name='senate-detail'),
    url(r'^society/(?P<slug>[\w-]+)/$', SocietyView.as_view(), name='society-detail'),
]

acac_backend/src/oauth/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView)
from .views import (ProfileDetailView, ProfileEditView, SocialLinkCreateView, SocialLinkUpdateView,
                    SocialLinkDeleteView, RegisterView, AccountActivationView, get_activation_link, SessionView)

app_name = 'oauth'

urlpatterns = [
    url(r'^session/$', SessionView.as_view(), name='session'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^(?P<roll>[\w]+)/get/$', get_activation_link, name='get-act-link'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\']+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        AccountActivationView.as_view(), name='activate'),
    url(r'^sociallink/add/$', SocialLinkCreateView.as_view(), name='link-add'),
    url(r'^(?P<roll>[\w]+)/$', ProfileDetailView.as_view(), name='detail'),
    url(r'^(?P<roll>[\w]+)/edit/$', ProfileEditView.as_view(), name='edit'),
    url(r'sociallink/(?P<username>[\w.-]+)-(?P<social_media>[\w]{2})/$', SocialLinkUpdateView.as_view(),
        name='link-edit'),
    url(r'sociallink/(?P<username>[\w.-]+)-(?P<social_media>[\w]{2})/delete/$', SocialLinkDeleteView.as_view(),
        name='link-delete'),
]

urlpatterns += [
    url(r'^password-reset/$', PasswordResetView.as_view(
        template_name='oauth/password_reset_form.html',
        email_template_name='oauth/mixins/password_reset_email.html',
        subject_template_name='oauth/mixins/password_reset_subject.txt',
        success_url=reverse_lazy('oauth:password_reset_done')
    ), name='password_reset'),
    url(r'^reset/done/$', PasswordResetDoneView.as_view(template_name='oauth/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(
            template_name='oauth/password_reset_confirm.html',
            success_url=reverse_lazy('oauth:password_reset_complete')), name='password_reset_confirm'),
    url(r'^reset/complete/$', PasswordResetCompleteView.as_view(template_name='oauth/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^password-change/$', PasswordChangeView.as_view(
        template_name='oauth/password_change_form.html',
        success_url=reverse_lazy('oauth:password_change_done')), name='password_change'),
    url(r'^password-change/done/$',
        PasswordChangeDoneView.as_view(template_name='oauth/password_change_done.html'), name='password_change_done')
]

acac_backend/src/events/models.py
from django.db import models
from main.models import Society


class Event(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    location = models.CharField(max_length=64)
    date = models.DateTimeField()
    society = models.ForeignKey(Society, null=True, blank=True, default=None, on_delete=models.CASCADE,
                             help_text="Leave blank to make this a general event.")
    published = models.BooleanField(default=True)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.name

acac_backend/src/main/models.py
import datetime
from django.db import models
from django.core.validators import RegexValidator
from oauth.models import UserProfile
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from versatileimagefield.fields import VersatileImageField
from photologue.models import Gallery

YEAR_CHOICES = []
for r in range(2008, (datetime.datetime.now().year + 2)):
    YEAR_CHOICES.append((str(r), r))

SKIN_CHOICES = (
    ('white-skin', 'White'),
    ('black-skin', 'Black'),
    ('cyan-skin', 'Cyan'),
    ('mdb-skin', 'MDB'),
    ('deep-purple-skin', 'Deep Purple'),
    ('navy-blue-skin', 'Navy Blue'),
    ('pink-skin', 'Pink'),
    ('indigo-skin', 'Indigo'),
    ('light-blue-skin', 'Light Blue'),
    ('grey-skin', 'Grey'),
)


class Faculty(models.Model):
    #validators
    contact = RegexValidator(r'^[0-9]{10}$', message='Not a valid number!')
    # Database Model
    name = models.CharField(max_length=128)
    email = models.EmailField(default=None)
    cover = VersatileImageField(upload_to='cover', blank=True, null=True)
    avatar = VersatileImageField(upload_to='avatar',blank=True, null=True)
    phone = models.CharField(max_length=10, validators=[contact])

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Faculty"

    def __str__(self):
        return self.name


class Board(models.Model):
    # Validators
    valid_year = RegexValidator(r'^[0-9]{4}$', message='Not a valid year!')
    # Model
    name = models.CharField(max_length=128)
    description = RichTextUploadingField(blank=True)
    cover = VersatileImageField('Cover', upload_to='board_%Y', help_text="Upload high quality picture")
    skin = models.CharField(max_length=32, choices=SKIN_CHOICES, blank=True, default='mdb-skin',
                            help_text="Choose a skin while displaying board page.")
    secretary = models.ForeignKey(UserProfile, related_name='secy',
                                        limit_choices_to={'user__is_staff': True}, null=True, blank=True,
                                        on_delete=models.SET_NULL)
    vice_president = models.ForeignKey(UserProfile, related_name='vice_president',
                                        limit_choices_to={'user__is_staff': True}, null=True, blank=True,
                                        on_delete=models.SET_NULL)
    president = models.ForeignKey(Faculty, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    report_link = models.URLField(help_text='Add a drive link to show on board page', null=True, blank=True)
    constitution_link = models.URLField(help_text='Add a drive link of the Constitution to show on board page', null=True, blank=True)
    gallery = models.ForeignKey(Gallery, blank=True, null=True, on_delete=models.SET_NULL,
                                help_text="Select a carousel gallery to link to this board.")
    custom_html = models.TextField(blank=True, null=True, default=None,
                                   help_text="Add custom HTML to view on board page.")
    slug = models.SlugField(unique=True, help_text="This will be used as URL. /board/slug")
    is_active = models.BooleanField(default=False)
    year = models.CharField(max_length=4, choices=YEAR_CHOICES, validators=[valid_year])

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Boards"

    def get_absolute_url(self):
        return reverse('main:board-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name + " - " + str(self.year)


class Society(models.Model):
    # Choices
    TYPE_CHOICES = (
        ('S', 'Society'),
        ('T', 'Team'),
    )
    # Model
    name = models.CharField(max_length=128)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    stype = models.CharField(max_length=1, choices=TYPE_CHOICES, default='S', help_text="Specify type as Society or Team.",
                             verbose_name="Type")
    description = RichTextUploadingField(blank=True)
    cover = VersatileImageField(upload_to='society_%Y', blank=True, null=True,
                                help_text="Upload high quality picture")
    skin = models.CharField(max_length=32, choices=SKIN_CHOICES, blank=True, default='mdb-skin',
                            help_text="Choose a skin while displaying society page.")
    student_coordinators = models.ManyToManyField(UserProfile, related_name='student_coordinator',
                                           limit_choices_to={'user__is_staff': True},
                                           blank=True, default=None,help_text="Select all the Student Coordinators of this society. ")
    core_members = models.ManyToManyField(UserProfile, blank=True)
    gallery = models.ForeignKey(Gallery, blank=True, null=True, on_delete=models.SET_NULL,
                                help_text="Select a gallery to link to this society.")
    resources_link = models.URLField(blank=True, null=True, default=None)
    custom_html = models.TextField(blank=True, null=True, default=None,
                                   help_text="Add custom HTML to view on club page.")
    slug = models.SlugField(unique=True, help_text="This will be used as URL. /society/slug")
    published = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Societies"

    @property
    def year(self):
        return self.board.year

    @property
    def is_active(self):
        return self.board.is_active

    def get_absolute_url(self):
        return reverse('main:soc-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name + " - " + str(self.year)


class Activity(models.Model):
    name = models.CharField(max_length=64)
    society = models.ForeignKey(Society, on_delete=models.CASCADE)
    description = RichTextUploadingField()
    custom_html = models.TextField(blank=True, null=True, default=None)

    class Meta:
        verbose_name_plural = 'Activities'

    def get_absolute_url(self):  # pragma: no use
        return reverse('main:activity-gallery', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' - ' + self.society.name


class Senate(models.Model):
    # Validators
    valid_year = RegexValidator(r'^[0-9]{4}$', message='Not a valid year!')
    # Model
    name = models.CharField(max_length=128)
    description = RichTextUploadingField(blank=True)
    cover = VersatileImageField('Cover', upload_to='society_%Y', help_text="Upload high quality picture")
    skin = models.CharField(max_length=32, choices=SKIN_CHOICES, blank=True, default='mdb-skin',
                            help_text="Choose a skin while displaying senate page.")
    gen_secy_senate = models.ForeignKey(UserProfile, related_name='gen_secy_senate', limit_choices_to={'user__is_staff': True},
                                null=True, blank=True, on_delete=models.SET_NULL)
    gen_secy_acac = models.ForeignKey(UserProfile, related_name='gen_secy_acac', limit_choices_to={'user__is_staff': True},
                                null=True, blank=True, on_delete=models.SET_NULL)
    report_link = models.URLField(help_text='Add a drive link to show on board page', null=True, blank=True)
    constitution_link = models.URLField(help_text='Add a drive link of constitution to show on board page', null=True, blank=True)
    custom_html = models.TextField(blank=True, null=True, default=None,
                                   help_text="Add custom HTML to view on board page.")
    slug = models.SlugField(unique=True, help_text="This will be used as URL. /senate/slug")
    is_active = models.BooleanField(default=False)
    year = models.CharField(max_length=4, choices=YEAR_CHOICES, validators=[valid_year])

    class Meta:
        ordering = ["-id"]

    def get_absolute_url(self):
        return reverse('main:senate-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name + ' - ' + self.year


class SenateMembership(models.Model):
    ROLE_CHOICES = (
        ('SECY', 'Student Secretary'),
        ('SER', 'Student Elected Representative'),
    )
    P_YEAR_CHOICES = (
        ('1', 'First Year'),
        ('2', 'Second Year'),
        ('3', 'Third Year'),
        ('4', 'Fourth Year'),
    )
    senate = models.ForeignKey(Senate, on_delete=models.CASCADE)
    userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    role = models.CharField(max_length=5, choices=ROLE_CHOICES)
    year = models.CharField(max_length=1, choices=P_YEAR_CHOICES)

    def __str__(self):
        return self.userprofile.user.get_full_name()


class SocialLink(models.Model):
    SM_CHOICES = (
        ('FB', 'Facebook'),
        ('TW', 'Twitter'),
        ('LI', 'LinkedIn'),
        ('GP', 'Google Plus'),
        ('IG', 'Instagram'),
        ('GH', 'GitHub'),
        ('YT', 'YouTube'),
    )
    FA_CHOICES = (
        ('fa fa-facebook', 'FB'),
        ('fa fa-twitter', 'TW'),
        ('fa fa-linkedin', 'LI'),
        ('fa fa-google-plus', 'GP'),
        ('fa fa-instagram', 'IG'),
        ('fa fa-github', 'GH'),
        ('fa fa-youtube', 'YT'),
    )
    IC_CHOICES = (
        ('fb-ic', 'FB'),
        ('tw-ic', 'TW'),
        ('li-ic', 'LI'),
        ('gplus-ic', 'GP'),
        ('ins-ic', 'IG'),
        ('git-ic', 'GH'),
        ('yt-ic', 'YT'),
    )
    society = models.ForeignKey(Society, on_delete=models.CASCADE)
    social_media = models.CharField(max_length=2, choices=SM_CHOICES)
    link = models.URLField()

    class Meta:
        ordering = ['social_media']

    def __str__(self):
        return self.society.name + ' - ' + self.get_social_media_display()

    def get_fai(self):
        for key, value in self.FA_CHOICES:
            if value == self.social_media:
                return key
        return 'fa fa-link'

    def get_sm_ic(self):
        for key, value in self.IC_CHOICES:
            if value == self.social_media:

acac_backend/src/news/models.py
from django.db import models
from oauth.models import UserProfile
from main.models import Society
from ckeditor_uploader.fields import RichTextUploadingField
from versatileimagefield.fields import VersatileImageField


class News(models.Model):
    title = models.CharField(max_length=128)
    cover = VersatileImageField(upload_to='news_%Y', blank=True, null=True,
                                help_text="Upload high quality image to use as cover photo.")
    author = models.ForeignKey(UserProfile, null=True, on_delete=models.SET_NULL)
    content = RichTextUploadingField()
    society = models.ForeignKey(Society, blank=True, null=True, on_delete=models.CASCADE, default=None,
                             help_text="Leave blank to make this a general news.")
    date = models.DateField(editable=True)

    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'news'

    def __str__(self):
        return self.title


class Update(models.Model):
    title = models.CharField(max_length=128)
    content = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

acac_backend/src/main/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'length': '10'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'length': '128'}))

    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'subject', 'message']

acac_backend/src/templates/main/mixins/activity_list_module.html
{% if not activity_list %}
    <h4 class="h4-responsive text-center">No activities to display</h4>
{% else %}
    <!--Accordion wrapper-->
    <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
        {% for activity in activity_list %}
            <div class="card">
                <div class="card-header" role="tab" id="heading{{ forloop.counter }}">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
                       href="#collapse{{ forloop.counter }}"
                       aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                        <h5 class="mb-0">
                            {{ activity.name }} <i class="fa fa-angle-down rotate-icon"></i>
                        </h5>
                    </a>
                </div>
                <div id="collapse{{ forloop.counter }}" class="collapse" role="tabpanel"
                     aria-labelledby="heading{{ forloop.counter }}">
                    <div id="description" class="card-block">
                        {{ activity.description|safe }}
                    </div>
                    {% if activity.custom_html %}
                        <div>
                            {{ activity.custom_html|safe }}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    <!--/.Accordion wrapper-->
{% endif %}

acac_backend/src/templates/main/mixins/club_gallery_mixin.html
<div class="col-md-12">
    <div class="mdb-lightbox">{% for photo in gallery.public %}
        <figure class="col-lg-3 col-md-4">
            <a href="{{ photo.get_lightbox_url }}"
               data-size="{{ size|default:'1275x850' }}">
                <img src="{{ photo.get_lightbox_url }}"
                     class="img-fluid">
            </a>
        </figure>{% endfor %}
    </div>
</div>

acac_backend/src/templates/main/mixins/club_member_card_mixin.html
{% load staticfiles %}
<div class="col-lg-4 col-md-6 mb-r">
    <div class="col-md-6 float-left">
        <div class="avatar">
            <a href="{{ userprofile.get_absolute_url }}">
                <img src="{% if userprofile.avatar %}{{ userprofile.avatar.crop.200x200 }}{% else %}{% static 'assets/others/missing.png' %}{% endif %}">
            </a>
        </div>
    </div>
    <div class="col-md-6 float-right">
        <h4><a class="black-text"
               href="{{ userprofile.get_absolute_url }}">{{ userprofile.user.get_full_name }}</a></h4>
        <p>{{ userprofile.about|linebreaks }}</p>
        <a class="icons-sm email-ic" href="mailto:{{ userprofile.user.email }}"><i
                class="fa fa-envelope-o"></i> </a>
        {% for link in userprofile.user.sociallink_set.all|slice:":5" %}
            <a class="icons-sm {{ link.get_sm_ic }}" target="_blank" href="{{ link.link }}"><i
                    class="{{ link.get_fai }}"></i></a>
        {% endfor %}
    </div>
</div>

acac_backend/src/templates/main/mixins/club_user_round_card_mixin.html
{% load staticfiles %}
<div class="col-lg-3 col-md-4 mt-1 wow fadeIn" data-wow-delay="0.5s" style="visibility: visible;">
    <div class="text-center">
        <div class="avatar">
            <a href="{{ userprofile.get_absolute_url }}">
                <img src="{% if userprofile.avatar %}{{ userprofile.avatar.crop.200x200 }}{% else %}{% static 'assets/others/missing.png' %}{% endif %}"
                                                                                      class="rounded-circle"></a>
        </div>
        <h4><a class="black-text" href="{{ userprofile.get_absolute_url }}">{{ userprofile.user.get_full_name }}</a></h4>
        <h5><i class="icons-sm-i fa fa-whatsapp green-text"></i><a
                href="https://api.whatsapp.com/send?phone=91{{ userprofile.phone }}">+91-{{ userprofile.phone }}</a>
        </h5>
        <h5>{{ designation|default:'' }}</h5>
        <p>{{ userprofile.about|linebreaks }}</p>
        <a class="icons-sm email-ic" href="mailto:{{ userprofile.user.email }}"><i
                class="fa fa-envelope-o"></i> </a>
        {% for link in userprofile.user.sociallink_set.all|slice:":4" %}
            <a class="icons-sm {{ link.get_sm_ic }}" target="_blank" href="{{ link.link }}"><i
                    class="{{ link.get_fai }}"></i></a>
        {% endfor %}
    </div>
</div>

acac_backend/src/templates/main/mixins/event_list_module.html
{% load humanize %}
<div class="d-flex justify-content-center mb-2 wow fadeIn" data-wow-delay="0.2s" style="visibility: visible;">
    <div><i class="fa fa-lightbulb-o fa-2x mr-2"></i></div>
    <div><h3 class="h3-responsive">Upcoming Event{{ event_list|pluralize }}</h3></div>
</div>
{% if not event_list %}
    <h4 class="h4-responsive text-center">No events to display</h4>
{% else %}
    <div class="list-group wow fadeIn" data-wow-delay="0.3s" style="visibility: visible;">
        <table class="table mb-0" id="events">
            <thead>
            <tr class="primary-color">
                <th class="text-center"><i class="fa fa-external-link"></i></th>
                <th>Name</th>
                <th class="text-center"><i class="fa fa-calendar-o"></i></th>
            </tr>
            </thead>
            <tbody>
            {% for event in event_list %}
                <tr class="list-group-item-action">
                    <td class="text-center"><a data-toggle="modal"
                                               data-target="#event-{{ forloop.counter }}"><i
                            class="fa fa-chevron-right"></i></a></td>
                    <td><a data-toggle="modal"
                           data-target="#event-{{ forloop.counter }}">{{ event.name|truncatechars:26 }}</a>
                    </td>
                    <td class="text-center">
                        <a data-toggle="modal" data-target="#event-{{ forloop.counter }}">
                            <small>{{ event.date|naturalday }}</small>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

acac_backend/src/templates/main/mixins/event_modal_mixin.html
{% load humanize %}
<!--Event Modals-->
{% for event in event_list %}
    <div class="modal fade" id="event-{{ forloop.counter }}" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog cascading-modal" role="document">
            <!--Content-->
            <div class="modal-content">
                <!--Header-->
                <div class="modal-header primary-color white-text">
                    <button type="button" class="close waves-effect waves-light" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="title">{{ event.club.name }} Event</h4>
                </div>
                <!--Body-->
                <div class="modal-body mb-0">
                    <h3 class="h3-responsive text-center mb-2">{{ event.name }}</h3>
                    <div class="container-fuild">
                        <div class="row text-center">
                            <div class="col-4"><i
                                    class="fa fa-calendar-o event-modal"></i>{{ event.date|naturalday }}</div>
                            <div class="col-4"><i class="fa fa-clock-o event-modal"></i>{{ event.date|time }}</div>
                            <div class="col-4"><i class="fa fa-map-marker event-modal"></i>{{ event.location }}
                            </div>
                        </div>
                    </div>
                    <p class="text-justify">{{ event.description|linebreaks }}</p>
                    <div class="text-right mt-1-half">
                        <button class="btn btn-sm btn-primary mb-1" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
            <!--/.Content-->
        </div>
    </div>
{% endfor %}
<!--End Modals-->

acac_backend/src/templates/main/mixins/news_list_club_module.html
{% load humanize %}
{% if not news_list %}
    <h4 class="h4-responsive text-center">No news to display</h4>
{% else %}
    <table class="table mb-0 pr-3 pl-3" id="news">
        <thead>
        <tr>
            <th class="text-center"><i class="fa fa-external-link"></i></th>
            <th>Title</th>
            <th class="text-center"><i class="fa fa-calendar-o"></i></th>
        </tr>
        </thead>
        <tbody>
        {% for news in news_list %}
            <tr class="list-group-item-action">
                <td class="text-center"><a data-toggle="modal"
                                           data-target="#news-{{ forloop.counter }}"><i
                        class="fa fa-chevron-right"></i></a></td>
                <td><a data-toggle="modal"
                       data-target="#news-{{ forloop.counter }}">{{ news.title|truncatechars:26 }}</a>
                </td>
                <td class="text-center">
                    <a data-toggle="modal" data-target="#news-{{ forloop.counter }}">
                        <small>{{ news.date|timesince }} ago</small>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

acac_backend/src/templates/main/mixins/news_modal_mixin.html
{% load humanize %}
<!--News Modals-->
{% for news in news_list %}
    <div class="modal fade" id="news-{{ forloop.counter }}" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog cascading-modal" role="document">
            <!--Content-->
            <div class="modal-content">
                <!--Header-->
                <div class="modal-header primary-color white-text">
                    <button type="button" class="close waves-effect waves-light" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="title">{{ news.club.name }} News</h4>
                </div>
                <!--Body-->
                <div class="modal-body mb-0">
                    <!--Card-->
                    <div class="card-overlay view hm-black-light"
                         style="background: url('{% include 'main/mixins/news_cover_src_mixin.html' with news=news %}') center; background-size: cover">
                        <!--Content-->
                        <div class="mask flex-center">
                            <div class="white-text text-center">
                                <div class="card-block">
                                    <h3 class="h3-responsive">{{ news.title }}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.Card-->
                    <div class="container-fuild pt-1">
                        <div class="row text-center">
                            <div class="col-6"><i class="fa fa-calendar-o news-modal"></i>{{ news.date|naturalday }}
                            </div>
                            <div class="col-6"><i class="fa fa-user news-modal"></i><a class="blue-grey-text"
                                                                                       href="{% url 'oauth:detail' news.author.roll %}">{{ news.author.user.get_full_name }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="pt-1" id="description">{{ news.content|safe }}</div>
                    <div class="text-right mt-1-half">
                        <button class="btn btn-sm btn-primary mb-1" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
            <!--/.Content-->
        </div>
    </div>
{% endfor %}
<!--End Modals-->